### ISSUE TITLE
Floating point exception computing flwafact

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/cism#3]
I'm getting floating point exceptions when running in debug mode, pointing to this line:

https://github.com/ESCOMP/cism/blob/a2c7ce0c2a7aa49909252ed82ba2b2920604e700/libglissade/glissade_velo_higher.F90#L1982

It looks like the problem is that flwa can be 0, and you can't take 0 to a negative power.

Example tests that demonstrate this issue: `SMS_D.f09_g17_gl4.T1850G.cheyenne_gnu` and `SMS_D.f09_g17_gl4.T1850G.cheyenne_intel`.

**Comment by billsacks** [comment]
These deaths are in model initialization.

**Comment by whlipscomb** [comment]
@billsacks, Please try the fix in the new branch, lipscomb/bug_fixes.

**Comment by billsacks** [comment]
Fixed by ff3091c6

Thanks, @whlipscomb . Your commit fixed this and the other issue. I have brought your branch to master/develop and am restarting testing.
