### ISSUE TITLE
bug in libglimmer/writestats.c

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CISM#59]
This issue appears when using the intel icx compiler.   The file writestats.c is missing a header ctype.h

Can a branch of  release-cism2.1.03 be created with this fix so that
I don't have to keep repeating to users that they need to make this change to run on derecho?

**Comment by whlipscomb** [comment]
@Katetc, would you be able to make this fix when you get back on Monday?

**Comment by Katetc** [comment]
Yes, I should be able to make this branch today. Just to clarify for posterity, though, this fix is currently on the main branch. But I understand that some users have older CESM tags.

**Comment by jedwards4b** [comment]
Yes - this fix is for cesm2.1.4 which is still widely used.

**Comment by Katetc** [comment]
Hi Jim, I have made the tags and tags for cism wrapper. They are now in the CSEG test and port database for the 2.1.5 and 2.2.2 releases. I'm going to go ahead and close this issue. Feel free to email me if you have any other problems!

**Comment by jedwards4b** [comment]
Thank you!
