### ISSUE TITLE
Runtime error with nag6.2 compiler on hobart

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/cism#6]
This problem comes in on hobart with the nag6.2 compiler. We didn't see this with the nag6.1 compiler.

This seems to mostly be for tests with DEBUG enabled.

Here's the runtime error message for /SMS_P48x1_D_Ld5.f10_f10_musgs.I2000Clm50Cn.hobart_nag.clm-default
```
/fs/cgd/data0/erik/ctsm_nfix/components/cism/source_cism/libglide/glide_diagnostics.F90, line 120: CaRuntime Error: /fs/cgd/data0/erik/ctsm_nfix/components/cism/source_cism/libglimmer/parallel_mpi.F90, line 4487: Assignment to XOUT affects dummy argument XIN
Program terminated by fatal error
/fs/cgd/data0/erik/ctsm_nfix/components/cism/source_cism/libglimmer/parallel_mpi.F90, line 4487: Error occurred in PARALLEL:PARALLEL_REDUCE_MAXLOC_INTEGER
/fs/cgd/data0/erik/ctsm_nfix/components/cism/source_cism/libglimmer/parallel_mpi.F90, line 3225: Called by PARALLEL:PARALLEL_LOCALINDEX
/fs/cgd/data0/erik/ctsm_nfix/components/cism/source_cism/libglide/glide_diagnostics.F90, line 120: Called by GLIDE_DIAGNOSTICS:GLIDE_INIT_DIAG
```

**Comment by billsacks** [comment]
Thanks, @ekluzek . I agree that this looks like a legitimate problem (https://stackoverflow.com/questions/7142233/fortran-passing-same-array-as-two-dummy-arguments-to-subroutine and https://software.intel.com/en-us/blogs/2009/07/10/doctor-fortran-in-ive-come-here-for-an-argument-side-2/). I'll take a look at this.
